name: Build and Release Executables
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        env:
          OS: ${{ matrix.os }}
        run: |
          pip install -r requirements.txt
          if [ "$OS" = "windows-latest" ]; then
              pip install pywin32
          elif [ "$OS" = "macos-13" ]; then
              pip install pyobjc
          fi
          python -m PyInstaller organiser.py
          ls -l dist/organiser/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/organiser/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./build

      - name: Rename Artifacts
        run: |
          mv build/windows-latest-build/organiser.exe build/organiser_windows.exe
          mv build/ubuntu-latest-build/organiser build/organiser_linux
          mv build/macos-13-build/organiser build/organiser_macos

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/organiser_windows.exe
            build/organiser_linux
            build/organiser_macos
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
