name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Build for Linux
          - os: ubuntu-latest
            artifact-name: linux
            pyinstaller-args: ""
          # Build for Windows x64
          - os: windows-latest
            artifact-name: win
            pyinstaller-args: ""
          # Build for macOS
          - os: macos-latest
            artifact-name: macos
            pyinstaller-args: ""
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        shell: bash
        env:
          PYINSTALLER_ARGS: ${{ matrix.pyinstaller-args }}
          CURRENT_OS: ${{ matrix.os }}
        run: |
          pip install -r requirements.txt
          # OS-specific dependencies
          if [[ "$CURRENT_OS" == "windows-latest" ]]; then
            pip install pywin32
          elif [[ "$CURRENT_OS" == "macos-latest" ]]; then
            pip install pyobjc
          fi
          # Build without cross-compiling
          python -m PyInstaller organiser.py $PYINSTALLER_ARGS
          ls -l dist/organiser/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}-build
          path: dist/organiser/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./build

      - name: Rename Artifacts
        shell: bash
        run: |
          # Windows x64 artifact
          if [ -d "build/win-build" ]; then
            mv build/win-build/organiser.exe build/organiser_windows.exe
          fi
          # Linux artifact
          if [ -d "build/linux-build" ]; then
            mv build/linux-build/organiser build/organiser_linux
          fi
          # macOS artifact
          if [ -d "build/macos-build" ]; then
            mv build/macos-build/organiser build/organiser_macos
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/organiser_windows.exe
            build/organiser_linux
            build/organiser_macos
          prerelease: ${{ contains(github.ref_name, '-') }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
